### ISSUE TITLE
Implement options to set custom channels.

### ISSUE THREAD

**Issue by JabDoesThings** [JabJabJab/Sledgehammer#37]
A YAML file will need to be implemented called 'chat_channels.yml'. This will allow administrators to make their own ChatChannels.

It will need to be structured as such:
```yml
chat_channels:
- name:
  permission:
  description:
  flags:
    public: true
    global: true
    history: true
```
