### ISSUE TITLE
Add Chat Module configuration.

### ISSUE THREAD

**Issue by JabDoesThings** [JabJabJab/Sledgehammer#53]
Have the Chat Module assign custom ChatChannels that allows admins to create custom channels.
```yml
channels:
- espanol:
    public: true
    global: true
    can_speak: true
- my_channel:
    public: false
    permission_node: "sledgehammer.chat.my_channel"
    global: false
    can_speak: true
```
